# val:
#   _target_: src.datasets.ExampleDataset
#   input_length: 1024
#   dataset_length: 15
#   n_classes: 10
#   name: "val"
#   instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.EvalDataset
  list_path: 'data/voxceleb_data/Vox1_O.txt'
  data_path: 'data/voxceleb_data'
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
