# val:
#   _target_: src.datasets.ExampleDataset
#   input_length: 1024
#   dataset_length: 15
#   n_classes: 10
#   name: "val"
#   instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.EvalDataset
  txt_path: 'data/crema-d_test/crema_test_list.txt'
  data_path: 'data/crema-d_test'
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
