test:
  _target_: src.datasets.EvalDataset
  list_path: 'data/cremad/cremad_test_list.txt'
  data_path: 'data/cremad/crema-d_test'
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
