train:
  _target_: src.datasets.TrainEmoDataset
  list_path: "my_data/crema_train/train_emo_list.txt"
  data_path: "my_data/crema_train"
  num_frames: 200     #'Duration of the input segments, eg: 200 for 2 second'
  start_label: 0
  name: "train"
  instance_transforms: ${transforms.instance_transforms.train}
voxceleb:
  _target_: src.datasets.EvalDataset
  list_path: 'my_data/voxceleb_data/Vox1_O1.txt'
  data_path: 'my_data/voxceleb_data'
  name: "voxceleb"
  instance_transforms: ${transforms.instance_transforms.inference}
cremad:
  _target_: src.datasets.EvalDataset
  list_path: 'my_data/crema-d_test/crema_test_list1.txt'
  data_path: 'my_data/crema-d_test'
  name: "crema-d"
  instance_transforms: ${transforms.instance_transforms.inference}
  