defaults:
  - model: ecapa_tdnn
  - metrics: inference
  - datasets: eval_dataset
  - dataloader: inference_dataloader
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["data_object_1", "data_object_2"]    # which tensors should be on device (ex. GPU)
  device: auto    # device name or "auto"
  save_path: "example"  # any name here, can be a dataset name
  seed: 1
  from_pretrained: "data/weights/ecapatdnn_weights.pth"   # path to the pretrained model
