train:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.NoiseAug
        num_frames: 200
        musan_path: "data/noise_aug/musan"
        rir_path: "data/noise_aug/simulated_rirs"
inference: null
