train:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.FeatureExtractor
        name: "microsoft/wavlm-base-plus-sv"
inference:
  data_object_1: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.FeatureExtractor
        name: "microsoft/wavlm-base-plus-sv"
  data_object_2: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.FeatureExtractor
        name: "microsoft/wavlm-base-plus-sv"